name: Install component from github

on:
    workflow_dispatch

jobs:
    do-install:
        runs-on: ubuntu-latest
        name: Do the install
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            - name: Install UV
              uses: astral-sh/setup-uv@v7
            - name: Install Pulumi
              uses: pulumi/actions@v6
              with: 
                pulumi-version: "v3.218.0"
            - name: Run pulumi about
              run: pulumi about
            - name: Run pulumi install
              run: pulumi install
            - name: Pulumi Auth
              uses: pulumi/auth-actions@v1
              with:
                organization: demo
                requested-token-type: urn:pulumi:token-type:access_token:personal
            - name: Pulumi Preview
              run: pulumi preview -s demo/dev